version: '2'
services:
    testapp2-app:
        image: testapp2
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://testapp2-mariadb:3306/testapp2
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testapp2-mariadb:
        extends:
            file: mariadb.yml
            service: testapp2-mariadb
